[data]
data=./Data/SEED/len_150/10_20131130/
dataset=SEED
seed=7
batch_size=128
shuffle=True
window_length=150
cls=3

[model]
num_of_vertices=62
hidden_dim=16
num_heads=1
dropout_disactive=0.6
strides=3

[train]
description=len150_s10
seed=22
learning_rate=1e-3
weight_decay_rate=1e-4
lr_decay_rate=0.9
epochs=500
check_gradient=
print_every=10
lr_decay_every=10
patience=66
save=./garage/SEED/s10/
expid=1
max_grad_norm=5.0
log_file=./logs/log_seed10_





    
   
